### ISSUE TITLE
Score mismatch between PMML file and H2O Mojo prediction

### ISSUE THREAD

**Issue by shiva2110** [jpmml/jpmml-h2o#10]
Hi,
I am seeing inconsistency between the PMML file predicted score and H2O Mojo file predicted score for exactly same feature map. I am using flow UI to get predicted score from H2O mojo file, and the difference in score I am seeing is large, for example, (0.005 with H2O v/s 0.90 with Pmml) for exact same feature values.  could you please help here ?

**Comment by vruusmann** [comment]
> I am seeing inconsistency between the PMML file predicted score and H2O Mojo file predicted 

Whatever the problem is, it is located on your end. I cannot be more specific, because you're not showing any code.

The JPMML-H2O library has ample integration test coverage, which proves that the predictions of all supported model types are reproducible within 1e-14 absolute/relative error.

See here: https://github.com/jpmml/jpmml-h2o/tree/master/src/test/java/org/jpmml/h2o
